npx hardhat run --network mainnet scripts/core/10*       >> output.txt &&
npx hardhat run --network mainnet scripts/core/11*       >> output.txt &&
npx hardhat run --network mainnet scripts/core/12*       >> output.txt &&
npx hardhat run --network mainnet scripts/core/13*       >> output.txt &&
npx hardhat run --network mainnet scripts/core/14*       >> output.txt &&
npx hardhat run --network mainnet scripts/core/15*       >> output.txt &&
npx hardhat run --network mainnet scripts/core/16*       >> output.txt &&
npx hardhat run --network mainnet scripts/core/17*       >> output.txt &&
npx hardhat run --network mainnet scripts/core/18*       >> output.txt &&
npx hardhat run --network mainnet scripts/operations/20* >> output.txt &&
npx hardhat run --network mainnet scripts/operations/21* >> output.txt &&
npx hardhat run --network mainnet scripts/operations/22* >> output.txt &&
npx hardhat run --network mainnet scripts/operations/30* >> output.txt &&
npx hardhat run --network mainnet scripts/operations/31* >> output.txt &&
npx hardhat run --network mainnet scripts/operations/32* >> output.txt &&
npx hardhat run --network mainnet scripts/operations/33* >> output.txt &&
npx hardhat run --network mainnet scripts/operations/34* >> output.txt &&
npx hardhat run --network mainnet scripts/strategies/40* >> output.txt &&
npx hardhat run --network mainnet scripts/strategies/41* >> output.txt
