npx hardhat run --network kovan mocks/01* >> output.txt
npx hardhat run --network kovan core/10* >> output.txt
npx hardhat run --network kovan core/11* >> output.txt
npx hardhat run --network kovan mocks/02* >> output.txt
npx hardhat run --network kovan core/12* >> output.txt
npx hardhat run --network kovan core/13* >> output.txt
npx hardhat run --network kovan core/14* >> output.txt
npx hardhat run --network kovan core/15* >> output.txt
npx hardhat run --network kovan core/16* >> output.txt
npx hardhat run --network kovan core/17* >> output.txt
npx hardhat run --network kovan core/18* >> output.txt
npx hardhat run --network kovan operations/20* >> output.txt
npx hardhat run --network kovan operations/21* >> output.txt
npx hardhat run --network kovan operations/22* >> output.txt
npx hardhat run --network kovan operations/30* >> output.txt
npx hardhat run --network kovan operations/31* >> output.txt
npx hardhat run --network kovan operations/32* >> output.txt
npx hardhat run --network kovan operations/33* >> output.txt
npx hardhat run --network kovan operations/34* >> output.txt
npx hardhat run --network kovan strategies/40* >> output.txt
npx hardhat run --network kovan strategies/41* >> output.txt

