npx hardhat run --network localhost core/10*       >> output.txt
npx hardhat run --network localhost core/11*       >> output.txt
npx hardhat run --network localhost core/12*       >> output.txt
npx hardhat run --network localhost core/13*       >> output.txt
npx hardhat run --network localhost core/14*       >> output.txt
npx hardhat run --network localhost core/15*       >> output.txt
npx hardhat run --network localhost core/16*       >> output.txt
npx hardhat run --network localhost core/17*       >> output.txt
npx hardhat run --network localhost core/18*       >> output.txt
npx hardhat run --network localhost operations/20* >> output.txt
npx hardhat run --network localhost operations/21* >> output.txt
npx hardhat run --network localhost operations/22* >> output.txt
npx hardhat run --network localhost operations/30* >> output.txt
npx hardhat run --network localhost operations/31* >> output.txt
npx hardhat run --network localhost operations/32* >> output.txt
npx hardhat run --network localhost operations/33* >> output.txt
npx hardhat run --network localhost operations/34* >> output.txt
npx hardhat run --network localhost strategies/40* >> output.txt
npx hardhat run --network localhost strategies/41* >> output.txt

