[profile.default]
src = 'src'
out = 'artifacts'
libs = ["node_modules", "lib"]
rpc_endpoints = { mainnet = "${MAINNET_RPC}" }
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@yield-protocol/=node_modules/@yield-protocol/',
    'dss-interfaces/=node_modules/dss-interfaces/',
    'erc3156/=node_modules/erc3156/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'hardhat/=node_modules/hardhat/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config