// SPDX-License-Identifier: GPL-3.0-or-later
pragma solidity >=0.8.13;

import "@yield-protocol/vault-v2/src/modules/HealerModule.sol";
import "@yield-protocol/vault-v2/src/modules/RepayFromLadleModule.sol";
import "@yield-protocol/vault-v2/src/oracles/accumulator/AccumulatorMultiOracle.sol";
import "@yield-protocol/vault-v2/src/oracles/chainlink/ChainlinkMultiOracle.sol";
import "@yield-protocol/vault-v2/src/oracles/chainlink/ChainlinkUSDMultiOracle.sol";
import "@yield-protocol/vault-v2/src/oracles/chainlink/ChainlinkL2USDMultiOracle.sol";
import "@yield-protocol/vault-v2/src/oracles/compound/CompoundMultiOracle.sol";
import "@yield-protocol/vault-v2/src/oracles/composite/CompositeMultiOracle.sol";
import "@yield-protocol/vault-v2/src/oracles/compound/CTokenMultiOracle.sol";
import "@yield-protocol/vault-v2/src/oracles/uniswap/UniswapV3Oracle.sol";
import "@yield-protocol/vault-v2/src/oracles/lido/LidoOracle.sol";
import "@yield-protocol/vault-v2/src/oracles/lido/IWstETH.sol";
import "@yield-protocol/vault-v2/src/oracles/yearn/YearnVaultMultiOracle.sol";
import "@yield-protocol/vault-v2/src/oracles/yearn/IYvToken.sol";
// import "@yield-protocol/vault-v2/src/oracles/crab/CrabOracle.sol";
import "@yield-protocol/vault-v2/src/oracles/yieldspace/YieldSpaceMultiOracle.sol";
// import "@yield-protocol/vault-v2/src/oracles/rocket/RETHOracle.sol";
import "@yield-protocol/vault-v2/src/other/tether/TetherJoin.sol";
import "@yield-protocol/vault-v2/src/other/notional/NotionalJoin.sol";
import "@yield-protocol/vault-v2/src/other/notional/NotionalMultiOracle.sol";
import "@yield-protocol/vault-v2/src/other/notional/Transfer1155Module.sol";
import "@yield-protocol/vault-v2/src/other/notional/ERC1155Mock.sol";
import "@yield-protocol/vault-v2/src/modules/WrapEtherModule.sol";
import "@yield-protocol/vault-v2/src/utils/Giver.sol";
import "@yield-protocol/vault-v2/src/Join.sol";
import "@yield-protocol/vault-v2/src/FlashJoin.sol";
import "@yield-protocol/vault-v2/src/FYToken.sol";
import "@yield-protocol/vault-v2/src/Cauldron.sol";
import "@yield-protocol/vault-v2/src/Ladle.sol";
import "@yield-protocol/vault-v2/src/Witch.sol";
import "@yield-protocol/yieldspace-tv/src/YieldMath.sol";
import "@yield-protocol/yieldspace-tv/src/Pool/Pool.sol";
import "@yield-protocol/yieldspace-tv/src/Pool/Modules/PoolNonTv.sol";
import "@yield-protocol/yieldspace-tv/src/Pool/Modules/PoolYearnVault.sol";
import "@yield-protocol/yieldspace-tv/src/Pool/Modules/PoolEuler.sol";
import "@yield-protocol/yieldspace-tv/src/oracle/PoolOracle.sol";
import "@yield-protocol/utils-v2/src/utils/Timelock.sol";
import "@yield-protocol/utils-v2/src/utils/EmergencyBrake.sol";
import "@yield-protocol/utils-v2/src/utils/Assert.sol";
import "@yield-protocol/strategy-v2/src/Strategy.sol";
// import "@yield-protocol/vault-v2/contracts/oracles/strategy/StrategyOracle.sol";
import "@yield-protocol/vault-v2/src/other/contango/ContangoLadle.sol";
import "@yield-protocol/vault-v2/src/other/contango/ContangoWitch.sol";
// import "@yield-protocol/yvarb/contracts/YieldStEthLever.sol";
// import "@yield-protocol/yvarb/contracts/YieldNotionalLever.sol";
import "@yield-protocol/vault-v2/src/variable/VRCauldron.sol";
import "@yield-protocol/vault-v2/src/variable/VRLadle.sol";
import "@yield-protocol/vault-v2/src/variable/VRWitch.sol";
import "@yield-protocol/vault-v2/src/variable/VYToken.sol";
import "@openzeppelin/contracts/proxy/ERC1967/ERC1967Proxy.sol";