name: CI

on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Build-Test-Regressions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache - cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            modules/liquidator/target
          key: ${{ runner.os }}-cargo2-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo2-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache - yarn root
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-root5-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-root5-

      - name: Get yarn cache directory path modules liquidator
        id: yarn-cache-dir-path-ml
        run: |
          cd modules/liquidator
          echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache - yarn modules/liquidator
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path-ml.outputs.dir }}
          key: ${{ runner.os }}-yarn-modules-liquidator4-${{ hashFiles('modules/liquidator/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-modules-liquidator4-

      - name: Build
        run: |
          cd ${{ github.workspace }}
          make --version
          make -j

      - name: Test
        run: |
          cd ${{ github.workspace }}
          make -j test

      - name: Regressions
        env:
          INFURA_ETHEREUM_MAINNET: ${{ secrets.INFURA_ETHEREUM_MAINNET }}
          INFURA_ARBITRUM_MAINNET: ${{ secrets.INFURA_ARBITRUM_MAINNET }}
        run: |
          cd ${{ github.workspace }}
          echo "{\"eth-mainnet\": \"$INFURA_ETHEREUM_MAINNET\", \"arb-mainnet\": \"$INFURA_ARBITRUM_MAINNET\"}" > .alchemyKey
          python -m json.tool .alchemyKey /dev/null
          make -j1 -Oline regressions

      - name: Upload regression test logs
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: regression-logs
          path: /tmp/flash_liquidator_test*
          retention-days: 5
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache - yarn root
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-lint4-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-lint4-

      - name: Lint
        run: |
          cd ${{ github.workspace }}
          make node_modules/.installed
          yarn lint:ts
